/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import java.io.FileWriter;
import java.io.IOException;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class Cadastro extends javax.swing.JFrame {

    Arma produto = new Arma("", "", "", "", "", "", 0);

    /**
     * Creates new form Tela
     */
    public Cadastro() {
        initComponents();

        jTextFieldLogradouroFornecedor.setDocument(new EntradaDeCaracteres(20));
        jTextFieldCepFornecedor.setDocument(new EntradaDeNumeros(8));
        jTextFieldNumeroFornecedor.setDocument(new EntradaDeNumeros(3));
        jTextFieldCidadeFornecedor.setDocument(new EntradaDeCaracteres(15));
        jTextFieldBairroFornecedor.setDocument(new EntradaDeCaracteres(15));

        jTextFieldNomeArma.setDocument(new EntradaDeCaracteres(40));
        jTextFieldFabricanteArma.setDocument(new EntradaDeCaracteres(40));

        jTextFieldNomeFantasiaFornecedor.setDocument(new EntradaDeCaracteres(20));
        jTextFieldRazaoSocialFornecedor.setDocument(new EntradaDeCaracteres(20));
        jTextFieldCnpjFornecedor.setDocument(new EntradaDeNumeros(14));
        jTextFieldTelefone1Fornecedor.setDocument(new EntradaDeNumeros(11));
        jTextFieldTelefone2Fornecedor.setDocument(new EntradaDeNumeros(11));
        jTextFieldeMailFornecedor.setDocument(new EntradaDeCaracteres(20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneSist = new javax.swing.JTabbedPane();
        jPanelCadastroFornecedor = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNomeFantasiaFornecedor = new javax.swing.JTextField();
        jTextFieldRazaoSocialFornecedor = new javax.swing.JTextField();
        jTextFieldCnpjFornecedor = new javax.swing.JTextField();
        jTextFieldLogradouroFornecedor = new javax.swing.JTextField();
        jTextFieldBairroFornecedor = new javax.swing.JTextField();
        jTextFieldCepFornecedor = new javax.swing.JTextField();
        jTextFieldNumeroFornecedor = new javax.swing.JTextField();
        jTextFieldCidadeFornecedor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldTelefone1Fornecedor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldTelefone2Fornecedor = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldeMailFornecedor = new javax.swing.JTextField();
        jButtonCadastrarFornecedor = new javax.swing.JButton();
        jComboBoxEstadoFornecedor = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanelCadastrarArma = new javax.swing.JPanel();
        jLabelNomeArma = new javax.swing.JLabel();
        jTextFieldNomeArma = new javax.swing.JTextField();
        jLabelTipoArma = new javax.swing.JLabel();
        jLabelCalibreArma = new javax.swing.JLabel();
        jSpinnerCalibreArma = new javax.swing.JSpinner();
        jLabelCapacidadeArma = new javax.swing.JLabel();
        jSpinnerCapacidade = new javax.swing.JSpinner();
        jLabelComprimentArma = new javax.swing.JLabel();
        jSpinnerComprimentArma = new javax.swing.JSpinner();
        jLabelFabricanteArma = new javax.swing.JLabel();
        jTextFieldFabricanteArma = new javax.swing.JTextField();
        jButtonCadastrarArma = new javax.swing.JButton();
        jComboBoxTipoArma = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerQuantidadeArma = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItemCadastrar = new javax.swing.JMenuItem();
        jMenuItemPesquisarAlterarEstoque = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fornecedor");

        jLabel7.setText("Nome Fantasia*:");

        jLabel8.setText("Razão Social*:");

        jLabel9.setText("CNPJ*:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Endereco");

        jLabel11.setText("Logradouro*:");

        jLabel12.setText("Bairro*:");

        jLabel13.setText("CEP*:");

        jLabel14.setText("Numero*:");

        jLabel15.setText("Cidade*:");

        jTextFieldNomeFantasiaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFantasiaFornecedorActionPerformed(evt);
            }
        });

        jTextFieldRazaoSocialFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRazaoSocialFornecedorActionPerformed(evt);
            }
        });

        jTextFieldCnpjFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCnpjFornecedorActionPerformed(evt);
            }
        });

        jTextFieldBairroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroFornecedorActionPerformed(evt);
            }
        });

        jLabel16.setText("Estado*:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Contato");

        jLabel18.setText("Telefone 1*:");

        jLabel19.setText("Telefone 2:");

        jTextFieldTelefone2Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefone2FornecedorActionPerformed(evt);
            }
        });

        jLabel20.setText("E-Mail*:");

        jTextFieldeMailFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldeMailFornecedorActionPerformed(evt);
            }
        });

        jButtonCadastrarFornecedor.setText("Cadastrar Fornecedor");
        jButtonCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarFornecedorActionPerformed(evt);
            }
        });

        jComboBoxEstadoFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "xx", "SP", "RJ", "RS", "MG" }));
        jComboBoxEstadoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoFornecedorActionPerformed(evt);
            }
        });

        jLabel2.setText("* = obrigatorio");

        javax.swing.GroupLayout jPanelCadastroFornecedorLayout = new javax.swing.GroupLayout(jPanelCadastroFornecedor);
        jPanelCadastroFornecedor.setLayout(jPanelCadastroFornecedorLayout);
        jPanelCadastroFornecedorLayout.setHorizontalGroup(
            jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldNomeFantasiaFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jTextFieldRazaoSocialFornecedor))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(20, 20, 20)
                                        .addComponent(jTextFieldLogradouroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel13))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCepFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addGap(31, 31, 31)
                                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBairroFornecedor)
                                    .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNumeroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 155, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18))
                    .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jButtonCadastrarFornecedor))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                                        .addComponent(jTextFieldTelefone1Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldTelefone2Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldeMailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelCadastroFornecedorLayout.setVerticalGroup(
            jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNomeFantasiaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldRazaoSocialFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldLogradouroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldBairroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldCepFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldNumeroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldTelefone1Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldTelefone2Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldeMailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrarFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jTabbedPaneSist.addTab("Fornecedor", jPanelCadastroFornecedor);

        jLabelNomeArma.setText("Nome*:");

        jLabelTipoArma.setText("Tipo*:");

        jLabelCalibreArma.setText("Calibre (mm)*:");

        jSpinnerCalibreArma.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        jLabelCapacidadeArma.setText("Capacidade:");

        jSpinnerCapacidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 300, 1));

        jLabelComprimentArma.setText("Comprimento Total (mm)*:");

        jSpinnerComprimentArma.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9000, 11));

        jLabelFabricanteArma.setText("Fabricante*:");

        jButtonCadastrarArma.setText("Cadastrar");
        jButtonCadastrarArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarArmaActionPerformed(evt);
            }
        });

        jComboBoxTipoArma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<tipo>", "Pistola", "Espingarda", "Submetralhadora" }));

        jLabel1.setText("* = obrigatorio");

        jLabel3.setText("Quantidade*:");

        jSpinnerQuantidadeArma.setModel(new javax.swing.SpinnerNumberModel(0, 0, 88, 1));

        javax.swing.GroupLayout jPanelCadastrarArmaLayout = new javax.swing.GroupLayout(jPanelCadastrarArma);
        jPanelCadastrarArma.setLayout(jPanelCadastrarArmaLayout);
        jPanelCadastrarArmaLayout.setHorizontalGroup(
            jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarArmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrarArma)
                    .addComponent(jLabel1)
                    .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastrarArmaLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerQuantidadeArma, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastrarArmaLayout.createSequentialGroup()
                            .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastrarArmaLayout.createSequentialGroup()
                                    .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCapacidadeArma)
                                        .addComponent(jLabelCalibreArma))
                                    .addGap(61, 61, 61))
                                .addGroup(jPanelCadastrarArmaLayout.createSequentialGroup()
                                    .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelComprimentArma)
                                        .addComponent(jLabelFabricanteArma)
                                        .addComponent(jLabelNomeArma)
                                        .addComponent(jLabelTipoArma))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelCadastrarArmaLayout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(jTextFieldFabricanteArma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldNomeArma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxTipoArma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelCadastrarArmaLayout.createSequentialGroup()
                                    .addGap(72, 72, 72)
                                    .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSpinnerComprimentArma, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpinnerCapacidade, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSpinnerCalibreArma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))))))))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanelCadastrarArmaLayout.setVerticalGroup(
            jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarArmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeArma)
                    .addComponent(jTextFieldNomeArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoArma)
                    .addComponent(jComboBoxTipoArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCalibreArma)
                    .addComponent(jSpinnerCalibreArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCapacidadeArma)
                    .addComponent(jSpinnerCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComprimentArma)
                    .addComponent(jSpinnerComprimentArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFabricanteArma)
                    .addComponent(jTextFieldFabricanteArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastrarArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerQuantidadeArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButtonCadastrarArma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jTabbedPaneSist.addTab("Cadastro de Arma", jPanelCadastrarArma);

        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });

        jMenuItemCadastrar.setText("Cadastrar");
        jMenuItemCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemCadastrar);

        jMenuItemPesquisarAlterarEstoque.setText("Pesquisar/Alterar Estoque");
        jMenuItemPesquisarAlterarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarAlterarEstoqueActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemPesquisarAlterarEstoque);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneSist)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneSist)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @throws JAXBException
     * @param evt
     */
    private void jButtonCadastrarArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarArmaActionPerformed

        if (jTextFieldNomeArma.toString().equals("")
                || jComboBoxTipoArma.getSelectedItem().toString().equals("<tipo>")
                || ((Number) jSpinnerCalibreArma.getValue()).intValue() == 0
                || ((Number) jSpinnerCapacidade.getValue()).intValue() == 0
                || ((Number) jSpinnerComprimentArma.getValue()).intValue() == 0
                || jTextFieldFabricanteArma.toString().equals("")
                || ((Number) jSpinnerQuantidadeArma.getValue()).intValue() == 0) {

            JOptionPane.showMessageDialog(rootPane, "Algum campo obrigatorio não foi preenchido", "Cadastro", WIDTH);

        } else {
            produto.setNome(jTextFieldNomeArma.getText());
            produto.setTipo(jComboBoxTipoArma.getName());
            produto.setCalibre(jSpinnerCalibreArma.getValue().toString());
            produto.setCapacidade(jSpinnerCapacidade.getValue().toString());
            produto.setComprimentoTotal(jSpinnerComprimentArma.getValue().toString());
            produto.setFabricante(jTextFieldFabricanteArma.getText());
            produto.setQuantidade(produto.getQuantidade() + 1);

            if (produto.ficoTudoBunito() == true) {
                JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!", "Cadastro", WIDTH);
                try {
                    relatorio();
                } catch (JAXBException | IOException ex) {
                    Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar!", "cadastro", WIDTH);
            }

        }

        jTextFieldNomeArma.setText("");
        jTextFieldFabricanteArma.setText("");
        jSpinnerCalibreArma.setValue(0);
        jSpinnerCapacidade.setValue(0);
        jSpinnerComprimentArma.setValue(0);
        jComboBoxTipoArma.setSelectedItem("<tipo>");
    }//GEN-LAST:event_jButtonCadastrarArmaActionPerformed

    private void jComboBoxEstadoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoFornecedorActionPerformed
    }//GEN-LAST:event_jComboBoxEstadoFornecedorActionPerformed

    private void jButtonCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarFornecedorActionPerformed
        Endereco endereco = new Endereco("", "", "", "", "", "");

        if (jTextFieldLogradouroFornecedor.toString().equals("")
                || jTextFieldCepFornecedor.toString().equals("")
                || jTextFieldNumeroFornecedor.toString().equals("")
                || jTextFieldCidadeFornecedor.toString().equals("")
                || jComboBoxEstadoFornecedor.getSelectedItem().toString().equals("xx")
                || jTextFieldNomeFantasiaFornecedor.toString().equals("")
                || jTextFieldRazaoSocialFornecedor.toString().equals("")
                || jTextFieldCnpjFornecedor.toString().equals("")
                || jTextFieldeMailFornecedor.toString().equals("")) {

            JOptionPane.showMessageDialog(rootPane, "Algum campo não foi preenchido", "Atencao!!!", WIDTH);

        } else {

            endereco.setLogradouro(jTextFieldLogradouroFornecedor.getText());
            endereco.setComplemento(jTextFieldBairroFornecedor.getText());
            endereco.setNumero(jTextFieldNumeroFornecedor.getText());
            endereco.setCep(jTextFieldCepFornecedor.getText());
            endereco.setCidade(jTextFieldCidadeFornecedor.getText());
            endereco.setEstado(jComboBoxEstadoFornecedor.getSelectedItem().toString());

            if (endereco.fivouBonito() == true) {
                JOptionPane.showMessageDialog(rootPane, "Cadastro Realizado", "Cadastro", WIDTH);

            } else {

                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar", "Cadastro", WIDTH);
            }

        }

        jTextFieldLogradouroFornecedor.setText("");
        jTextFieldBairroFornecedor.setText("");
        jTextFieldCepFornecedor.setText("");
        jTextFieldNumeroFornecedor.setText("");
        jTextFieldCidadeFornecedor.setText("");
        jComboBoxEstadoFornecedor.setSelectedItem("xx");

        jTextFieldNomeFantasiaFornecedor.setText("");
        jTextFieldRazaoSocialFornecedor.setText("");
        jTextFieldCnpjFornecedor.setText("");
        jTextFieldTelefone1Fornecedor.setText("");
        jTextFieldTelefone2Fornecedor.setText("");
        jTextFieldeMailFornecedor.setText("");

    }//GEN-LAST:event_jButtonCadastrarFornecedorActionPerformed

    public void relatorio() throws JAXBException, IOException {

        JAXBContext context = JAXBContext.newInstance(Arma.class);
        Marshaller marshal = context.createMarshaller();

        marshal.marshal(produto, System.out);

        FileWriter writer = new FileWriter("Arma.xml");
        writer.write("Arma.xml");
        marshal.marshal(produto, writer);
    }

    private void jTextFieldeMailFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldeMailFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldeMailFornecedorActionPerformed

    private void jTextFieldTelefone2FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefone2FornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefone2FornecedorActionPerformed

    private void jTextFieldBairroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroFornecedorActionPerformed

    private void jTextFieldCnpjFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCnpjFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCnpjFornecedorActionPerformed

    private void jTextFieldRazaoSocialFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRazaoSocialFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRazaoSocialFornecedorActionPerformed

    private void jTextFieldNomeFantasiaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFantasiaFornecedorActionPerformed

    }//GEN-LAST:event_jTextFieldNomeFantasiaFornecedorActionPerformed

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed


    }//GEN-LAST:event_jMenuActionPerformed

    private void jMenuItemCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarActionPerformed

        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenuItemCadastrarActionPerformed

    private void jMenuItemPesquisarAlterarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarAlterarEstoqueActionPerformed
        Estoque estoque = new Estoque();
        estoque.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemPesquisarAlterarEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarArma;
    private javax.swing.JButton jButtonCadastrarFornecedor;
    private javax.swing.JComboBox jComboBoxEstadoFornecedor;
    private javax.swing.JComboBox jComboBoxTipoArma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCalibreArma;
    private javax.swing.JLabel jLabelCapacidadeArma;
    private javax.swing.JLabel jLabelComprimentArma;
    private javax.swing.JLabel jLabelFabricanteArma;
    private javax.swing.JLabel jLabelNomeArma;
    private javax.swing.JLabel jLabelTipoArma;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastrar;
    private javax.swing.JMenuItem jMenuItemPesquisarAlterarEstoque;
    private javax.swing.JPanel jPanelCadastrarArma;
    private javax.swing.JPanel jPanelCadastroFornecedor;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSpinner jSpinnerCalibreArma;
    private javax.swing.JSpinner jSpinnerCapacidade;
    private javax.swing.JSpinner jSpinnerComprimentArma;
    private javax.swing.JSpinner jSpinnerQuantidadeArma;
    private javax.swing.JTabbedPane jTabbedPaneSist;
    private javax.swing.JTextField jTextFieldBairroFornecedor;
    private javax.swing.JTextField jTextFieldCepFornecedor;
    private javax.swing.JTextField jTextFieldCidadeFornecedor;
    private javax.swing.JTextField jTextFieldCnpjFornecedor;
    private javax.swing.JTextField jTextFieldFabricanteArma;
    private javax.swing.JTextField jTextFieldLogradouroFornecedor;
    private javax.swing.JTextField jTextFieldNomeArma;
    private javax.swing.JTextField jTextFieldNomeFantasiaFornecedor;
    private javax.swing.JTextField jTextFieldNumeroFornecedor;
    private javax.swing.JTextField jTextFieldRazaoSocialFornecedor;
    private javax.swing.JTextField jTextFieldTelefone1Fornecedor;
    private javax.swing.JTextField jTextFieldTelefone2Fornecedor;
    private javax.swing.JTextField jTextFieldeMailFornecedor;
    // End of variables declaration//GEN-END:variables

}
